-- =========================================================
-- EZY1 PRODUCTION POSTGRESQL CANONICAL DATA MIGRATION
-- Generated: 2026-10-01T19:36:32.656Z
-- =========================================================

BEGIN;

SET session_replication_role = 'replica';

-- 1. Users
INSERT INTO "User" ("id", "username", "email", "name", "phone", "passwordHash", "role", "status", "walletBalance", "createdAt", "updatedAt") VALUES (1, 'user_1', 'admin@ezy1.com', 'Admin', '9999999999', NULL, 'ADMIN'::"UserRole", 'ACTIVE'::"AccountStatus", 0.00, NOW(), NOW()) ON CONFLICT ("id") DO UPDATE SET "name" = EXCLUDED."name", "phone" = EXCLUDED."phone", "walletBalance" = EXCLUDED."walletBalance";
INSERT INTO "User" ("id", "username", "email", "name", "phone", "passwordHash", "role", "status", "walletBalance", "createdAt", "updatedAt") VALUES (2, 'user_2', 'ramesh@shop.com', 'Ramesh', '8888888888', NULL, 'VENDOR'::"UserRole", 'ACTIVE'::"AccountStatus", 0.00, NOW(), NOW()) ON CONFLICT ("id") DO UPDATE SET "name" = EXCLUDED."name", "phone" = EXCLUDED."phone", "walletBalance" = EXCLUDED."walletBalance";
INSERT INTO "User" ("id", "username", "email", "name", "phone", "passwordHash", "role", "status", "walletBalance", "createdAt", "updatedAt") VALUES (3, 'user_3', '9876543210@customer.ezy1.com', 'Rahul Sharma', '9876543210', NULL, 'CUSTOMER'::"UserRole", 'ACTIVE'::"AccountStatus", 100.00, NOW(), NOW()) ON CONFLICT ("id") DO UPDATE SET "name" = EXCLUDED."name", "phone" = EXCLUDED."phone", "walletBalance" = EXCLUDED."walletBalance";
INSERT INTO "User" ("id", "username", "email", "name", "phone", "passwordHash", "role", "status", "walletBalance", "createdAt", "updatedAt") VALUES (4, 'user_4', 'customer@ezy1.com', 'Rahul Sharma', NULL, NULL, 'CUSTOMER'::"UserRole", 'ACTIVE'::"AccountStatus", 100.00, NOW(), NOW()) ON CONFLICT ("id") DO UPDATE SET "name" = EXCLUDED."name", "phone" = EXCLUDED."phone", "walletBalance" = EXCLUDED."walletBalance";
INSERT INTO "User" ("id", "username", "email", "name", "phone", "passwordHash", "role", "status", "walletBalance", "createdAt", "updatedAt") VALUES (5, 'user_5', '7379609531@customer.ezy1.com', 'Customer 9531', '7379609531', NULL, 'CUSTOMER'::"UserRole", 'ACTIVE'::"AccountStatus", 100.00, NOW(), NOW()) ON CONFLICT ("id") DO UPDATE SET "name" = EXCLUDED."name", "phone" = EXCLUDED."phone", "walletBalance" = EXCLUDED."walletBalance";
INSERT INTO "User" ("id", "username", "email", "name", "phone", "passwordHash", "role", "status", "walletBalance", "createdAt", "updatedAt") VALUES (12, 'user_12', '9123456789@customer.ezy1.com', 'Priya Singh', '9123456789', NULL, 'CUSTOMER'::"UserRole", 'ACTIVE'::"AccountStatus", 100.00, NOW(), NOW()) ON CONFLICT ("id") DO UPDATE SET "name" = EXCLUDED."name", "phone" = EXCLUDED."phone", "walletBalance" = EXCLUDED."walletBalance";
INSERT INTO "User" ("id", "username", "email", "name", "phone", "passwordHash", "role", "status", "walletBalance", "createdAt", "updatedAt") VALUES (13, 'rohan_783', 'rohan_783@test.com', 'Rohan Verma', '9873227560', '8820c0107cf56148d8e8810f06f7e0e4:dcca9ad7634a7571259ebd2ab1bfcaf7949b9db7fdfba310ade0cf98e908b6416e701602b6449d73f58e099439ad34c66005a3f1be1895fbaf6c285a96b3ad00', 'CUSTOMER'::"UserRole", 'ACTIVE'::"AccountStatus", 100.00, NOW(), NOW()) ON CONFLICT ("id") DO UPDATE SET "name" = EXCLUDED."name", "phone" = EXCLUDED."phone", "walletBalance" = EXCLUDED."walletBalance";
INSERT INTO "User" ("id", "username", "email", "name", "phone", "passwordHash", "role", "status", "walletBalance", "createdAt", "updatedAt") VALUES (14, 'user_9876537126', 'user_9876537126@ezy1.site', 'Ananya Sharma', '9876537126', NULL, 'CUSTOMER'::"UserRole", 'ACTIVE'::"AccountStatus", 0.00, NOW(), NOW()) ON CONFLICT ("id") DO UPDATE SET "name" = EXCLUDED."name", "phone" = EXCLUDED."phone", "walletBalance" = EXCLUDED."walletBalance";
INSERT INTO "User" ("id", "username", "email", "name", "phone", "passwordHash", "role", "status", "walletBalance", "createdAt", "updatedAt") VALUES (15, 'user_9876574614', 'user_9876574614@ezy1.site', 'Ananya Sharma', '9876574614', NULL, 'CUSTOMER'::"UserRole", 'ACTIVE'::"AccountStatus", 0.00, NOW(), NOW()) ON CONFLICT ("id") DO UPDATE SET "name" = EXCLUDED."name", "phone" = EXCLUDED."phone", "walletBalance" = EXCLUDED."walletBalance";
INSERT INTO "User" ("id", "username", "email", "name", "phone", "passwordHash", "role", "status", "walletBalance", "createdAt", "updatedAt") VALUES (16, 'user_9876588102', 'user_9876588102@ezy1.site', 'Ananya Sharma', '9876588102', NULL, 'CUSTOMER'::"UserRole", 'ACTIVE'::"AccountStatus", 0.00, NOW(), NOW()) ON CONFLICT ("id") DO UPDATE SET "name" = EXCLUDED."name", "phone" = EXCLUDED."phone", "walletBalance" = EXCLUDED."walletBalance";
INSERT INTO "User" ("id", "username", "email", "name", "phone", "passwordHash", "role", "status", "walletBalance", "createdAt", "updatedAt") VALUES (17, 'user_9876514989', 'user_9876514989@ezy1.site', 'Ananya Sharma', '9876514989', NULL, 'CUSTOMER'::"UserRole", 'ACTIVE'::"AccountStatus", 0.00, NOW(), NOW()) ON CONFLICT ("id") DO UPDATE SET "name" = EXCLUDED."name", "phone" = EXCLUDED."phone", "walletBalance" = EXCLUDED."walletBalance";
INSERT INTO "User" ("id", "username", "email", "name", "phone", "passwordHash", "role", "status", "walletBalance", "createdAt", "updatedAt") VALUES (18, 'user_9876560136', 'user_9876560136@ezy1.site', 'Ananya Sharma', '9876560136', NULL, 'CUSTOMER'::"UserRole", 'ACTIVE'::"AccountStatus", 0.00, NOW(), NOW()) ON CONFLICT ("id") DO UPDATE SET "name" = EXCLUDED."name", "phone" = EXCLUDED."phone", "walletBalance" = EXCLUDED."walletBalance";
INSERT INTO "User" ("id", "username", "email", "name", "phone", "passwordHash", "role", "status", "walletBalance", "createdAt", "updatedAt") VALUES (19, 'user_9876536359', 'user_9876536359@ezy1.site', 'Ananya Sharma', '9876536359', NULL, 'CUSTOMER'::"UserRole", 'ACTIVE'::"AccountStatus", 0.00, NOW(), NOW()) ON CONFLICT ("id") DO UPDATE SET "name" = EXCLUDED."name", "phone" = EXCLUDED."phone", "walletBalance" = EXCLUDED."walletBalance";
INSERT INTO "User" ("id", "username", "email", "name", "phone", "passwordHash", "role", "status", "walletBalance", "createdAt", "updatedAt") VALUES (20, 'user_9876520303', 'user_9876520303@ezy1.site', 'Ananya Sharma', '9876520303', NULL, 'CUSTOMER'::"UserRole", 'ACTIVE'::"AccountStatus", 0.00, NOW(), NOW()) ON CONFLICT ("id") DO UPDATE SET "name" = EXCLUDED."name", "phone" = EXCLUDED."phone", "walletBalance" = EXCLUDED."walletBalance";

-- 2. Partners
INSERT INTO "Partner" ("id", "partnerUserId", "name", "businessName", "email", "phone", "city", "address", "role", "providerType", "status", "isVerified", "createdAt", "updatedAt") VALUES (1, 'EZY-P-10001', 'Alka & Rahul Yadav', 'EZY1 Platform Headquarters', 'admin@ezy1.in', '9876543210', 'Bengaluru', 'HQ Tech Park', 'ADMIN'::"UserRole", 'ADMIN'::"PartnerType", 'ACTIVE'::"PartnerStatus", true, NOW(), NOW()) ON CONFLICT ("id") DO UPDATE SET "businessName" = EXCLUDED."businessName", "phone" = EXCLUDED."phone";
INSERT INTO "Partner" ("id", "partnerUserId", "name", "businessName", "email", "phone", "city", "address", "role", "providerType", "status", "isVerified", "createdAt", "updatedAt") VALUES (2, 'EZY-P-10002', 'Ramesh Sharma', 'Sharma Kirana Store', 'sharma.kirana@partner.ezy1.in', '9876543211', 'Mumbai', '123 Market Rd', 'PARTNER'::"UserRole", 'GROCERY'::"PartnerType", 'ACTIVE'::"PartnerStatus", true, NOW(), NOW()) ON CONFLICT ("id") DO UPDATE SET "businessName" = EXCLUDED."businessName", "phone" = EXCLUDED."phone";
INSERT INTO "Partner" ("id", "partnerUserId", "name", "businessName", "email", "phone", "city", "address", "role", "providerType", "status", "isVerified", "createdAt", "updatedAt") VALUES (3, 'EZY-P-10003', 'Krishnan Nair', 'Nair Ayurveda & Pharma', 'nair.pharma@partner.ezy1.in', '9876543212', 'Thiruvananthapuram', '45 Temple St', 'PARTNER'::"UserRole", 'PHARMACY'::"PartnerType", 'ACTIVE'::"PartnerStatus", true, NOW(), NOW()) ON CONFLICT ("id") DO UPDATE SET "businessName" = EXCLUDED."businessName", "phone" = EXCLUDED."phone";
INSERT INTO "Partner" ("id", "partnerUserId", "name", "businessName", "email", "phone", "city", "address", "role", "providerType", "status", "isVerified", "createdAt", "updatedAt") VALUES (4, 'EZY-P-10004', 'Suresh Sharma', 'Suresh Electricals & Fixes', 'suresh.services@partner.ezy1.in', '9876543213', 'Bengaluru', '77 MG Rd', 'PARTNER'::"UserRole", 'SERVICE_PROVIDER'::"PartnerType", 'ACTIVE'::"PartnerStatus", true, NOW(), NOW()) ON CONFLICT ("id") DO UPDATE SET "businessName" = EXCLUDED."businessName", "phone" = EXCLUDED."phone";
INSERT INTO "Partner" ("id", "partnerUserId", "name", "businessName", "email", "phone", "city", "address", "role", "providerType", "status", "isVerified", "createdAt", "updatedAt") VALUES (5, 'EZY-P-10005', 'Rajesh Kumar', 'Rajesh Fleet & Logistics', 'rajesh.transport@partner.ezy1.in', '9876543214', 'Delhi', '99 Ring Rd', 'PARTNER'::"UserRole", 'DELIVERY'::"PartnerType", 'ACTIVE'::"PartnerStatus", true, NOW(), NOW()) ON CONFLICT ("id") DO UPDATE SET "businessName" = EXCLUDED."businessName", "phone" = EXCLUDED."phone";
INSERT INTO "Partner" ("id", "partnerUserId", "name", "businessName", "email", "phone", "city", "address", "role", "providerType", "status", "isVerified", "createdAt", "updatedAt") VALUES (6, 'EZY-P-10006', 'Dr. Vikram Sethi', 'Apex Health Diagnostic Lab', 'vikram.1789580117991@apexlab.in', '9876517991', 'Mumbai', '101 Medical Center, Mumbai', 'PARTNER'::"UserRole", 'HOSPITAL'::"PartnerType", 'ACTIVE'::"PartnerStatus", true, NOW(), NOW()) ON CONFLICT ("id") DO UPDATE SET "businessName" = EXCLUDED."businessName", "phone" = EXCLUDED."phone";
INSERT INTO "Partner" ("id", "partnerUserId", "name", "businessName", "email", "phone", "city", "address", "role", "providerType", "status", "isVerified", "createdAt", "updatedAt") VALUES (7, 'EZY-P-10007', 'Dr. Vikram Sethi', 'Apex Health Diagnostic Lab', 'vikram.1789580219685@apexlab.in', '9876519685', 'Mumbai', '101 Medical Center, Mumbai', 'PARTNER'::"UserRole", 'RESTAURANT'::"PartnerType", 'ACTIVE'::"PartnerStatus", true, NOW(), NOW()) ON CONFLICT ("id") DO UPDATE SET "businessName" = EXCLUDED."businessName", "phone" = EXCLUDED."phone";
INSERT INTO "Partner" ("id", "partnerUserId", "name", "businessName", "email", "phone", "city", "address", "role", "providerType", "status", "isVerified", "createdAt", "updatedAt") VALUES (8, 'EZY-P-10008', 'Dr. Vikram Sethi', 'Apex Health Diagnostic Lab', 'vikram.1789580353838@apexlab.in', '9876553838', 'Mumbai', '101 Medical Center, Mumbai', 'PARTNER'::"UserRole", 'FRUITS_VEGETABLES'::"PartnerType", 'INACTIVE'::"PartnerStatus", true, NOW(), NOW()) ON CONFLICT ("id") DO UPDATE SET "businessName" = EXCLUDED."businessName", "phone" = EXCLUDED."phone";
INSERT INTO "Partner" ("id", "partnerUserId", "name", "businessName", "email", "phone", "city", "address", "role", "providerType", "status", "isVerified", "createdAt", "updatedAt") VALUES (9, 'EZY-P-10009', 'Dr. Vikram Sethi', 'Apex Health Diagnostic Lab', 'vikram.1789580444281@apexlab.in', '9876544281', 'Mumbai', '101 Medical Center, Mumbai', 'PARTNER'::"UserRole", 'CAFE'::"PartnerType", 'INACTIVE'::"PartnerStatus", true, NOW(), NOW()) ON CONFLICT ("id") DO UPDATE SET "businessName" = EXCLUDED."businessName", "phone" = EXCLUDED."phone";
INSERT INTO "Partner" ("id", "partnerUserId", "name", "businessName", "email", "phone", "city", "address", "role", "providerType", "status", "isVerified", "createdAt", "updatedAt") VALUES (10, 'EZY-P-10010', 'Dr. Vikram Sethi', 'Apex Health Diagnostic Lab', 'vikram.1789581629518@apexlab.in', '9876529518', 'Mumbai', '101 Medical Center, Mumbai', 'PARTNER'::"UserRole", 'BOOKS'::"PartnerType", 'INACTIVE'::"PartnerStatus", true, NOW(), NOW()) ON CONFLICT ("id") DO UPDATE SET "businessName" = EXCLUDED."businessName", "phone" = EXCLUDED."phone";
INSERT INTO "Partner" ("id", "partnerUserId", "name", "businessName", "email", "phone", "city", "address", "role", "providerType", "status", "isVerified", "createdAt", "updatedAt") VALUES (11, 'EZY-P-10011', 'Dr. Vikram Sethi', 'Apex Health Diagnostic Lab', 'vikram.1789584927536@apexlab.in', '9876527536', 'Mumbai', '101 Medical Center, Mumbai', 'PARTNER'::"UserRole", 'ELECTRONICS'::"PartnerType", 'INACTIVE'::"PartnerStatus", true, NOW(), NOW()) ON CONFLICT ("id") DO UPDATE SET "businessName" = EXCLUDED."businessName", "phone" = EXCLUDED."phone";
INSERT INTO "Partner" ("id", "partnerUserId", "name", "businessName", "email", "phone", "city", "address", "role", "providerType", "status", "isVerified", "createdAt", "updatedAt") VALUES (12, 'EZY-P-10012', 'Meena Kapoor', 'Meena Designer Studio & Boutique', 'meena.fashion@partner.ezy1.in', '9876543221', 'Jaipur', 'Bapu Bazaar 5', 'PARTNER'::"UserRole", 'FASHION'::"PartnerType", 'ACTIVE'::"PartnerStatus", true, NOW(), NOW()) ON CONFLICT ("id") DO UPDATE SET "businessName" = EXCLUDED."businessName", "phone" = EXCLUDED."phone";
INSERT INTO "Partner" ("id", "partnerUserId", "name", "businessName", "email", "phone", "city", "address", "role", "providerType", "status", "isVerified", "createdAt", "updatedAt") VALUES (13, 'EZY-P-10013', 'Babulal Sweetmaker', 'Babulal Sweets & Chocolates', 'babulal.sweets@partner.ezy1.in', '9876543222', 'Varanasi', 'Godowlia Chowk', 'PARTNER'::"UserRole", 'SWEETS_CHOCOLATE'::"PartnerType", 'ACTIVE'::"PartnerStatus", true, NOW(), NOW()) ON CONFLICT ("id") DO UPDATE SET "businessName" = EXCLUDED."businessName", "phone" = EXCLUDED."phone";
INSERT INTO "Partner" ("id", "partnerUserId", "name", "businessName", "email", "phone", "city", "address", "role", "providerType", "status", "isVerified", "createdAt", "updatedAt") VALUES (14, 'EZY-P-10014', 'Dr. Vivek Malhotra', 'Malhotra Clinic & Wellness Centre', 'vivek.malhotra@partner.ezy1.in', '9876543223', 'Bengaluru', 'HSR Sector 1', 'PARTNER'::"UserRole", 'DOCTOR'::"PartnerType", 'ACTIVE'::"PartnerStatus", true, NOW(), NOW()) ON CONFLICT ("id") DO UPDATE SET "businessName" = EXCLUDED."businessName", "phone" = EXCLUDED."phone";
INSERT INTO "Partner" ("id", "partnerUserId", "name", "businessName", "email", "phone", "city", "address", "role", "providerType", "status", "isVerified", "createdAt", "updatedAt") VALUES (15, 'EZY-P-10015', 'Dr. Ritu Singhania', 'Apex Diagnostic & Path Lab', 'apex.lab@partner.ezy1.in', '9876543224', 'Delhi', 'Preet Vihar', 'PARTNER'::"UserRole", 'DIAGNOSTICS'::"PartnerType", 'ACTIVE'::"PartnerStatus", true, NOW(), NOW()) ON CONFLICT ("id") DO UPDATE SET "businessName" = EXCLUDED."businessName", "phone" = EXCLUDED."phone";
INSERT INTO "Partner" ("id", "partnerUserId", "name", "businessName", "email", "phone", "city", "address", "role", "providerType", "status", "isVerified", "createdAt", "updatedAt") VALUES (16, 'EZY-P-10016', 'Vikramaditya Roy', 'The Heritage Stay & Boutique Suites', 'heritage.hotel@partner.ezy1.in', '9876543225', 'Goa', 'Calangute Beach Rd', 'PARTNER'::"UserRole", 'HOTEL'::"PartnerType", 'ACTIVE'::"PartnerStatus", true, NOW(), NOW()) ON CONFLICT ("id") DO UPDATE SET "businessName" = EXCLUDED."businessName", "phone" = EXCLUDED."phone";
INSERT INTO "Partner" ("id", "partnerUserId", "name", "businessName", "email", "phone", "city", "address", "role", "providerType", "status", "isVerified", "createdAt", "updatedAt") VALUES (17, 'EZY-P-10017', 'Tanveer Ahmed', 'Paradise Tour & Himalayan Travels', 'paradise.travel@partner.ezy1.in', '9876543226', 'Srinagar', 'Dal Lake Boulevard', 'PARTNER'::"UserRole", 'TRAVEL'::"PartnerType", 'ACTIVE'::"PartnerStatus", true, NOW(), NOW()) ON CONFLICT ("id") DO UPDATE SET "businessName" = EXCLUDED."businessName", "phone" = EXCLUDED."phone";
INSERT INTO "Partner" ("id", "partnerUserId", "name", "businessName", "email", "phone", "city", "address", "role", "providerType", "status", "isVerified", "createdAt", "updatedAt") VALUES (18, 'EZY-P-10018', 'Anand Sharma', 'Devbhoomi Certified Local Guides', 'anand.guide@partner.ezy1.in', '9876543227', 'Rishikesh', 'Laxman Jhula Marg', 'PARTNER'::"UserRole", 'GUIDE'::"PartnerType", 'ACTIVE'::"PartnerStatus", true, NOW(), NOW()) ON CONFLICT ("id") DO UPDATE SET "businessName" = EXCLUDED."businessName", "phone" = EXCLUDED."phone";
INSERT INTO "Partner" ("id", "partnerUserId", "name", "businessName", "email", "phone", "city", "address", "role", "providerType", "status", "isVerified", "createdAt", "updatedAt") VALUES (19, 'EZY-P-10019', 'Gurmeet Singh', 'Royal Coach Bus Fleet Lines', 'royal.bus@partner.ezy1.in', '9876543228', 'Amritsar', 'Grand Trunk Road', 'PARTNER'::"UserRole", 'BUS'::"PartnerType", 'ACTIVE'::"PartnerStatus", true, NOW(), NOW()) ON CONFLICT ("id") DO UPDATE SET "businessName" = EXCLUDED."businessName", "phone" = EXCLUDED."phone";
INSERT INTO "Partner" ("id", "partnerUserId", "name", "businessName", "email", "phone", "city", "address", "role", "providerType", "status", "isVerified", "createdAt", "updatedAt") VALUES (20, 'EZY-P-10020', 'Harish Babu', 'FastTrack City & Intercity Rides', 'fasttrack.ride@partner.ezy1.in', '9876543229', 'Bengaluru', 'Electronic City Phase 2', 'PARTNER'::"UserRole", 'RIDE'::"PartnerType", 'ACTIVE'::"PartnerStatus", true, NOW(), NOW()) ON CONFLICT ("id") DO UPDATE SET "businessName" = EXCLUDED."businessName", "phone" = EXCLUDED."phone";
INSERT INTO "Partner" ("id", "partnerUserId", "name", "businessName", "email", "phone", "city", "address", "role", "providerType", "status", "isVerified", "createdAt", "updatedAt") VALUES (21, 'EZY-P-10021', 'EZY1 Operations Management', 'EZY1 Central Owner Operations', 'owner@ezy1.in', '9876543230', 'Bengaluru', 'EZY1 HQ Tower', 'OWNER'::"UserRole", 'OWNER'::"PartnerType", 'ACTIVE'::"PartnerStatus", true, NOW(), NOW()) ON CONFLICT ("id") DO UPDATE SET "businessName" = EXCLUDED."businessName", "phone" = EXCLUDED."phone";
INSERT INTO "Partner" ("id", "partnerUserId", "name", "businessName", "email", "phone", "city", "address", "role", "providerType", "status", "isVerified", "createdAt", "updatedAt") VALUES (22, 'EZY-P-10022', 'Dr. Vikram Sethi', 'Apex Health Diagnostic Lab', 'vikram.1789617816604@apexlab.in', '9876516604', 'Mumbai', '101 Medical Center, Mumbai', 'PARTNER'::"UserRole", 'DIAGNOSTIC_LAB'::"PartnerType", 'INACTIVE'::"PartnerStatus", true, NOW(), NOW()) ON CONFLICT ("id") DO UPDATE SET "businessName" = EXCLUDED."businessName", "phone" = EXCLUDED."phone";
INSERT INTO "Partner" ("id", "partnerUserId", "name", "businessName", "email", "phone", "city", "address", "role", "providerType", "status", "isVerified", "createdAt", "updatedAt") VALUES (23, 'EZY-P-10023', 'Dr. Vikram Sethi', 'Apex Health Diagnostic Lab', 'vikram.1789619741868@apexlab.in', '9876541868', 'Mumbai', '101 Medical Center, Mumbai', 'PARTNER'::"UserRole", 'DIAGNOSTIC_LAB'::"PartnerType", 'INACTIVE'::"PartnerStatus", true, NOW(), NOW()) ON CONFLICT ("id") DO UPDATE SET "businessName" = EXCLUDED."businessName", "phone" = EXCLUDED."phone";
INSERT INTO "Partner" ("id", "partnerUserId", "name", "businessName", "email", "phone", "city", "address", "role", "providerType", "status", "isVerified", "createdAt", "updatedAt") VALUES (24, 'EZY-P-10024', 'Dr. Vikram Sethi', 'Apex Health Diagnostic Lab', 'vikram.1789620525439@apexlab.in', '9876525439', 'Mumbai', '101 Medical Center, Mumbai', 'PARTNER'::"UserRole", 'DIAGNOSTIC_LAB'::"PartnerType", 'INACTIVE'::"PartnerStatus", true, NOW(), NOW()) ON CONFLICT ("id") DO UPDATE SET "businessName" = EXCLUDED."businessName", "phone" = EXCLUDED."phone";
INSERT INTO "Partner" ("id", "partnerUserId", "name", "businessName", "email", "phone", "city", "address", "role", "providerType", "status", "isVerified", "createdAt", "updatedAt") VALUES (25, 'EZY-P-10025', 'Dr. Vikram Sethi', 'Apex Health Diagnostic Lab', 'vikram.1789621720010@apexlab.in', '9876520010', 'Mumbai', '101 Medical Center, Mumbai', 'PARTNER'::"UserRole", 'DIAGNOSTIC_LAB'::"PartnerType", 'INACTIVE'::"PartnerStatus", true, NOW(), NOW()) ON CONFLICT ("id") DO UPDATE SET "businessName" = EXCLUDED."businessName", "phone" = EXCLUDED."phone";
INSERT INTO "Partner" ("id", "partnerUserId", "name", "businessName", "email", "phone", "city", "address", "role", "providerType", "status", "isVerified", "createdAt", "updatedAt") VALUES (26, 'EZY-P-10026', 'Dr. Vikram Sethi', 'Apex Health Diagnostic Lab', 'vikram.1789623608780@apexlab.in', '9876508780', 'Mumbai', '101 Medical Center, Mumbai', 'PARTNER'::"UserRole", 'DIAGNOSTIC_LAB'::"PartnerType", 'INACTIVE'::"PartnerStatus", true, NOW(), NOW()) ON CONFLICT ("id") DO UPDATE SET "businessName" = EXCLUDED."businessName", "phone" = EXCLUDED."phone";
INSERT INTO "Partner" ("id", "partnerUserId", "name", "businessName", "email", "phone", "city", "address", "role", "providerType", "status", "isVerified", "createdAt", "updatedAt") VALUES (27, 'EZY-P-10027', 'Dr. Vikram Sethi', 'Apex Health Diagnostic Lab', 'vikram.1790336896451@apexlab.in', '9876596451', 'Mumbai', '101 Medical Center, Mumbai', 'PARTNER'::"UserRole", 'DIAGNOSTIC_LAB'::"PartnerType", 'INACTIVE'::"PartnerStatus", true, NOW(), NOW()) ON CONFLICT ("id") DO UPDATE SET "businessName" = EXCLUDED."businessName", "phone" = EXCLUDED."phone";
INSERT INTO "Partner" ("id", "partnerUserId", "name", "businessName", "email", "phone", "city", "address", "role", "providerType", "status", "isVerified", "createdAt", "updatedAt") VALUES (28, 'EZY-P-10028', 'Dr. Vikram Sethi', 'Apex Health Diagnostic Lab', 'vikram.1790337150396@apexlab.in', '9876550396', 'Mumbai', '101 Medical Center, Mumbai', 'PARTNER'::"UserRole", 'DIAGNOSTIC_LAB'::"PartnerType", 'INACTIVE'::"PartnerStatus", true, NOW(), NOW()) ON CONFLICT ("id") DO UPDATE SET "businessName" = EXCLUDED."businessName", "phone" = EXCLUDED."phone";

-- 3. Products
INSERT INTO "Product" ("id", "partnerId", "categoryId", "name", "description", "price", "isAvailable", "createdAt", "updatedAt") VALUES (1, 1, 1, 'Aashirvaad Atta (5kg)', 'Whole wheat flour', 250.00, true, NOW(), NOW()) ON CONFLICT ("id") DO UPDATE SET "price" = EXCLUDED."price", "name" = EXCLUDED."name";
INSERT INTO "Product" ("id", "partnerId", "categoryId", "name", "description", "price", "isAvailable", "createdAt", "updatedAt") VALUES (2, 1, 1, 'Tata Salt (1kg)', 'Iodized salt', 25.00, true, NOW(), NOW()) ON CONFLICT ("id") DO UPDATE SET "price" = EXCLUDED."price", "name" = EXCLUDED."name";

-- 4. Orders
INSERT INTO "Order" ("id", "orderNumber", "userId", "partnerId", "subtotal", "totalAmount", "status", "paymentStatus", "createdAt", "updatedAt") VALUES (1, 'ORD-2026-00001', 3, 1, 399.00, 399.00, 'PENDING'::"OrderStatus", 'PAID'::"PaymentStatus", NOW(), NOW()) ON CONFLICT ("id") DO UPDATE SET "totalAmount" = EXCLUDED."totalAmount";
INSERT INTO "Order" ("id", "orderNumber", "userId", "partnerId", "subtotal", "totalAmount", "status", "paymentStatus", "createdAt", "updatedAt") VALUES (2, 'ORD-2026-00002', 3, 1, 399.00, 399.00, 'PENDING'::"OrderStatus", 'PAID'::"PaymentStatus", NOW(), NOW()) ON CONFLICT ("id") DO UPDATE SET "totalAmount" = EXCLUDED."totalAmount";
INSERT INTO "Order" ("id", "orderNumber", "userId", "partnerId", "subtotal", "totalAmount", "status", "paymentStatus", "createdAt", "updatedAt") VALUES (3, 'ORD-2026-00003', 3, 1, 399.00, 399.00, 'PENDING'::"OrderStatus", 'PAID'::"PaymentStatus", NOW(), NOW()) ON CONFLICT ("id") DO UPDATE SET "totalAmount" = EXCLUDED."totalAmount";
INSERT INTO "Order" ("id", "orderNumber", "userId", "partnerId", "subtotal", "totalAmount", "status", "paymentStatus", "createdAt", "updatedAt") VALUES (4, 'ORD-2026-00004', 3, 1, 399.00, 399.00, 'PENDING'::"OrderStatus", 'PAID'::"PaymentStatus", NOW(), NOW()) ON CONFLICT ("id") DO UPDATE SET "totalAmount" = EXCLUDED."totalAmount";
INSERT INTO "Order" ("id", "orderNumber", "userId", "partnerId", "subtotal", "totalAmount", "status", "paymentStatus", "createdAt", "updatedAt") VALUES (5, 'ORD-2026-00005', 3, 1, 399.00, 399.00, 'PENDING'::"OrderStatus", 'PAID'::"PaymentStatus", NOW(), NOW()) ON CONFLICT ("id") DO UPDATE SET "totalAmount" = EXCLUDED."totalAmount";
INSERT INTO "Order" ("id", "orderNumber", "userId", "partnerId", "subtotal", "totalAmount", "status", "paymentStatus", "createdAt", "updatedAt") VALUES (6, 'ORD-2026-00006', 3, 1, 399.00, 399.00, 'PENDING'::"OrderStatus", 'PAID'::"PaymentStatus", NOW(), NOW()) ON CONFLICT ("id") DO UPDATE SET "totalAmount" = EXCLUDED."totalAmount";
INSERT INTO "Order" ("id", "orderNumber", "userId", "partnerId", "subtotal", "totalAmount", "status", "paymentStatus", "createdAt", "updatedAt") VALUES (7, 'ORD-2026-00007', 3, 1, 399.00, 399.00, 'PENDING'::"OrderStatus", 'PAID'::"PaymentStatus", NOW(), NOW()) ON CONFLICT ("id") DO UPDATE SET "totalAmount" = EXCLUDED."totalAmount";
INSERT INTO "Order" ("id", "orderNumber", "userId", "partnerId", "subtotal", "totalAmount", "status", "paymentStatus", "createdAt", "updatedAt") VALUES (8, 'ORD-2026-00008', 3, 1, 399.00, 399.00, 'PENDING'::"OrderStatus", 'PAID'::"PaymentStatus", NOW(), NOW()) ON CONFLICT ("id") DO UPDATE SET "totalAmount" = EXCLUDED."totalAmount";
INSERT INTO "Order" ("id", "orderNumber", "userId", "partnerId", "subtotal", "totalAmount", "status", "paymentStatus", "createdAt", "updatedAt") VALUES (9, 'ORD-2026-00009', 17, 1, 1298.00, 1298.00, 'CONFIRMED'::"OrderStatus", 'PAID'::"PaymentStatus", NOW(), NOW()) ON CONFLICT ("id") DO UPDATE SET "totalAmount" = EXCLUDED."totalAmount";
INSERT INTO "Order" ("id", "orderNumber", "userId", "partnerId", "subtotal", "totalAmount", "status", "paymentStatus", "createdAt", "updatedAt") VALUES (10, 'ORD-2026-00010', 18, 1, 1298.00, 1298.00, 'CONFIRMED'::"OrderStatus", 'PAID'::"PaymentStatus", NOW(), NOW()) ON CONFLICT ("id") DO UPDATE SET "totalAmount" = EXCLUDED."totalAmount";
INSERT INTO "Order" ("id", "orderNumber", "userId", "partnerId", "subtotal", "totalAmount", "status", "paymentStatus", "createdAt", "updatedAt") VALUES (11, 'ORD-2026-00011', 19, 1, 1298.00, 1298.00, 'CONFIRMED'::"OrderStatus", 'PAID'::"PaymentStatus", NOW(), NOW()) ON CONFLICT ("id") DO UPDATE SET "totalAmount" = EXCLUDED."totalAmount";
INSERT INTO "Order" ("id", "orderNumber", "userId", "partnerId", "subtotal", "totalAmount", "status", "paymentStatus", "createdAt", "updatedAt") VALUES (12, 'ORD-2026-00012', 20, 1, 1298.00, 1298.00, 'CONFIRMED'::"OrderStatus", 'PAID'::"PaymentStatus", NOW(), NOW()) ON CONFLICT ("id") DO UPDATE SET "totalAmount" = EXCLUDED."totalAmount";

-- 5. Payments
INSERT INTO "Payment" ("id", "paymentNumber", "orderId", "userId", "amount", "currency", "gateway", "gatewayOrderId", "gatewayPaymentId", "status", "createdAt", "updatedAt") VALUES (1, 'PAY-2026-942867', 9, 17, 1298.00, 'INR', 'RAZORPAY'::"PaymentGateway", 'order_1790335501018_fpdhtx', 'pay_1790335501020', 'CAPTURED'::"PaymentStatus", NOW(), NOW()) ON CONFLICT ("id") DO UPDATE SET "status" = EXCLUDED."status";
INSERT INTO "Payment" ("id", "paymentNumber", "orderId", "userId", "amount", "currency", "gateway", "gatewayOrderId", "gatewayPaymentId", "status", "createdAt", "updatedAt") VALUES (2, 'PAY-2026-853824', 10, 18, 1298.00, 'INR', 'RAZORPAY'::"PaymentGateway", 'order_1790335952611_ttdl5k', 'pay_1790335952613', 'CAPTURED'::"PaymentStatus", NOW(), NOW()) ON CONFLICT ("id") DO UPDATE SET "status" = EXCLUDED."status";
INSERT INTO "Payment" ("id", "paymentNumber", "orderId", "userId", "amount", "currency", "gateway", "gatewayOrderId", "gatewayPaymentId", "status", "createdAt", "updatedAt") VALUES (3, 'PAY-2026-894350', 11, 19, 1298.00, 'INR', 'RAZORPAY'::"PaymentGateway", 'order_1790336259694_mb44u2', 'pay_1790336259696', 'CAPTURED'::"PaymentStatus", NOW(), NOW()) ON CONFLICT ("id") DO UPDATE SET "status" = EXCLUDED."status";
INSERT INTO "Payment" ("id", "paymentNumber", "orderId", "userId", "amount", "currency", "gateway", "gatewayOrderId", "gatewayPaymentId", "status", "createdAt", "updatedAt") VALUES (4, 'PAY-2026-696180', 12, 20, 1298.00, 'INR', 'RAZORPAY'::"PaymentGateway", 'order_1790863253368_m6tpm6', 'pay_1790863253371', 'CAPTURED'::"PaymentStatus", NOW(), NOW()) ON CONFLICT ("id") DO UPDATE SET "status" = EXCLUDED."status";

-- 6. Hospital Beds
INSERT INTO "HospitalBed" ("id", "hospitalName", "bedType", "totalBeds", "availableBeds", "dailyRate", "oxygenSupport", "ventilatorSupport", "city", "phone", "createdAt", "updatedAt") VALUES (1, NULL, 'ICU', 10, 5, 4500.00, false, false, 'Bengaluru', '0000000000', NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "HospitalBed" ("id", "hospitalName", "bedType", "totalBeds", "availableBeds", "dailyRate", "oxygenSupport", "ventilatorSupport", "city", "phone", "createdAt", "updatedAt") VALUES (2, NULL, 'ICU', 10, 5, 4500.00, false, false, 'Bengaluru', '0000000000', NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "HospitalBed" ("id", "hospitalName", "bedType", "totalBeds", "availableBeds", "dailyRate", "oxygenSupport", "ventilatorSupport", "city", "phone", "createdAt", "updatedAt") VALUES (3, NULL, 'GENERAL', 10, 5, 1200.00, false, false, 'Bengaluru', '0000000000', NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "HospitalBed" ("id", "hospitalName", "bedType", "totalBeds", "availableBeds", "dailyRate", "oxygenSupport", "ventilatorSupport", "city", "phone", "createdAt", "updatedAt") VALUES (4, NULL, 'DELUXE', 10, 5, 3000.00, false, false, 'Bengaluru', '0000000000', NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "HospitalBed" ("id", "hospitalName", "bedType", "totalBeds", "availableBeds", "dailyRate", "oxygenSupport", "ventilatorSupport", "city", "phone", "createdAt", "updatedAt") VALUES (5, NULL, 'EMERGENCY', 10, 5, 5000.00, false, false, 'Bengaluru', '0000000000', NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "HospitalBed" ("id", "hospitalName", "bedType", "totalBeds", "availableBeds", "dailyRate", "oxygenSupport", "ventilatorSupport", "city", "phone", "createdAt", "updatedAt") VALUES (6, NULL, 'EMERGENCY', 10, 5, 5000.00, false, false, 'Bengaluru', '0000000000', NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "HospitalBed" ("id", "hospitalName", "bedType", "totalBeds", "availableBeds", "dailyRate", "oxygenSupport", "ventilatorSupport", "city", "phone", "createdAt", "updatedAt") VALUES (7, NULL, 'EMERGENCY', 10, 5, 5500.00, false, false, 'Bengaluru', '0000000000', NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;

-- 7. Pharmacy Medicines
INSERT INTO "PharmacyMedicine" ("id", "name", "category", "manufacturer", "dosage", "price", "prescriptionRequired", "stockCount", "createdAt", "updatedAt") VALUES (1, 'Paracetamol 650mg', 'Analgesic', 'Ezy1 Pharma', 'Standard', 30.00, false, 100, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "PharmacyMedicine" ("id", "name", "category", "manufacturer", "dosage", "price", "prescriptionRequired", "stockCount", "createdAt", "updatedAt") VALUES (2, 'Amoxicillin 500mg', 'Antibiotic', 'Ezy1 Pharma', 'Standard', 120.00, false, 100, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "PharmacyMedicine" ("id", "name", "category", "manufacturer", "dosage", "price", "prescriptionRequired", "stockCount", "createdAt", "updatedAt") VALUES (3, 'Cetirizine 10mg', 'Antihistamine', 'Ezy1 Pharma', 'Standard', 45.00, false, 100, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;

-- 8. Restaurant Menu
INSERT INTO "RestaurantMenuItem" ("id", "name", "category", "price", "isVeg", "spicyLevel", "available", "createdAt", "updatedAt") VALUES (1, 'Hyderabadi Dum Biryani', 'Main Course', 280.00, false, 'Medium', true, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "RestaurantMenuItem" ("id", "name", "category", "price", "isVeg", "spicyLevel", "available", "createdAt", "updatedAt") VALUES (2, 'Paneer Butter Masala', 'Main Course', 220.00, true, 'Medium', true, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "RestaurantMenuItem" ("id", "name", "category", "price", "isVeg", "spicyLevel", "available", "createdAt", "updatedAt") VALUES (3, 'Garlic Naan (2 pcs)', 'Breads', 60.00, true, 'Medium', true, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;

-- 9. Hotels / Stays
INSERT INTO "Hotel" ("id", "name", "city", "address", "rating", "pricePerNight", "availableRooms", "createdAt", "updatedAt") VALUES (1, 'The Heritage Grand Suites', 'Bengaluru', 'MG Road, Central Bengaluru', 4.8, 2899.00, 6, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "Hotel" ("id", "name", "city", "address", "rating", "pricePerNight", "availableRooms", "createdAt", "updatedAt") VALUES (2, 'Bloom Suites Urban Stay', 'Bengaluru', 'Indiranagar 100ft Road', 4.6, 1899.00, 8, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "Hotel" ("id", "name", "city", "address", "rating", "pricePerNight", "availableRooms", "createdAt", "updatedAt") VALUES (3, 'Coorg Pine Mist Homestay', 'Madikeri', 'Estate Hilltop, Coorg', 4.9, 2400.00, 3, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "Hotel" ("id", "name", "city", "address", "rating", "pricePerNight", "availableRooms", "createdAt", "updatedAt") VALUES (4, 'Zostel Backpacker Hub', 'Bengaluru', 'Koramangala 5th Block', 4.5, 699.00, 12, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;

-- 10. Buses
INSERT INTO "Bus" ("id", "operator", "busType", "origin", "destination", "departureTime", "arrivalTime", "price", "availableSeats", "createdAt", "updatedAt") VALUES (1, 'Ezy1 Express', 'AC_SLEEPER', 'City Hub', 'Airport', '07:30 AM', '10:30 AM', 250.00, 16, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "Bus" ("id", "operator", "busType", "origin", "destination", "departureTime", "arrivalTime", "price", "availableSeats", "createdAt", "updatedAt") VALUES (2, 'Ezy1 Express', 'VOLVO_MULTI_AXLE', 'City Hub', 'Airport', '09:00 PM', '06:30 AM', 250.00, 9, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "Bus" ("id", "operator", "busType", "origin", "destination", "departureTime", "arrivalTime", "price", "availableSeats", "createdAt", "updatedAt") VALUES (3, 'Ezy1 Express', 'ELECTRIC', 'City Hub', 'Airport', '08:15 AM', '09:30 AM', 250.00, 21, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;

-- 11. Shared Rides
INSERT INTO "SharedRide" ("id", "driverName", "vehicleModel", "vehicleNumber", "origin", "destination", "pricePerSeat", "availableSeats", "createdAt", "updatedAt") VALUES (1, 'Aditya Sen (Software Engg)', 'Sedan', 'KA-01-EZ-1001', 'Koramangala', 'Whitefield', 120.00, 3, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "SharedRide" ("id", "driverName", "vehicleModel", "vehicleNumber", "origin", "destination", "pricePerSeat", "availableSeats", "createdAt", "updatedAt") VALUES (2, 'Deepika Rao (Product Designer)', 'Sedan', 'KA-01-EZ-1001', 'Koramangala', 'Whitefield', 120.00, 2, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "SharedRide" ("id", "driverName", "vehicleModel", "vehicleNumber", "origin", "destination", "pricePerSeat", "availableSeats", "createdAt", "updatedAt") VALUES (3, 'Karthik Nair (Consultant)', 'Sedan', 'KA-01-EZ-1001', 'Koramangala', 'Whitefield', 120.00, 2, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;

-- 12. Home Healthcare Services
INSERT INTO "HomeHealthcareService" ("id", "serviceName", "category", "price", "durationHours", "qualifications", "available", "createdAt", "updatedAt") VALUES (1, 'General Physician Home Visit', 'DOCTOR_AT_HOME', 500.00, 2, 'Certified RN', true, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "HomeHealthcareService" ("id", "serviceName", "category", "price", "durationHours", "qualifications", "available", "createdAt", "updatedAt") VALUES (2, 'Certified Nurse Visit at Home', 'NURSE_AT_HOME', 500.00, 2, 'Certified RN', true, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "HomeHealthcareService" ("id", "serviceName", "category", "price", "durationHours", "qualifications", "available", "createdAt", "updatedAt") VALUES (3, 'Physiotherapy & Mobility Session', 'PHYSIOTHERAPY', 500.00, 2, 'Certified RN', true, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "HomeHealthcareService" ("id", "serviceName", "category", "price", "durationHours", "qualifications", "available", "createdAt", "updatedAt") VALUES (4, 'Complete Full Body Blood Sample Collection', 'SAMPLE_COLLECTION', 500.00, 2, 'Certified RN', true, NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;

SET session_replication_role = 'DEFAULT';
COMMIT;
