/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ListingInput = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Nat,
});
export const Listing = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Nat,
});
export const VisitType = IDL.Variant({
  'clinic' : IDL.Null,
  'home' : IDL.Null,
});
export const BookAppointmentInput = IDL.Record({
  'doctorId' : IDL.Nat,
  'visitType' : VisitType,
  'notes' : IDL.Text,
  'dateTime' : IDL.Text,
});
export const AppointmentStatus = IDL.Variant({
  'scheduled' : IDL.Null,
  'cancelled' : IDL.Null,
  'completed' : IDL.Null,
});
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const Appointment = IDL.Record({
  'id' : IDL.Nat,
  'status' : AppointmentStatus,
  'doctorId' : IDL.Nat,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'visitType' : VisitType,
  'notes' : IDL.Text,
  'dateTime' : IDL.Text,
});
export const AvailabilitySlot = IDL.Record({
  'startTime' : IDL.Text,
  'endTime' : IDL.Text,
  'date' : IDL.Text,
  'isBooked' : IDL.Bool,
});
export const Doctor = IDL.Record({
  'id' : IDL.Nat,
  'availabilitySlots' : IDL.Vec(AvailabilitySlot),
  'name' : IDL.Text,
  'qualifications' : IDL.Vec(IDL.Text),
  'specialization' : IDL.Text,
  'rating' : IDL.Float64,
  'hourlyPrice' : IDL.Nat,
  'visitTypes' : IDL.Vec(VisitType),
});
export const Role = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'vendor' : IDL.Null,
  'driver' : IDL.Null,
});
export const UserPublic = IDL.Record({
  'id' : UserId,
  'preferredLanguage' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : Role,
  'savedAddresses' : IDL.Vec(IDL.Text),
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const RideStatus = IDL.Variant({
  'assigned' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const RideRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : RideStatus,
  'dropoffLocation' : IDL.Text,
  'userId' : UserId,
  'fare' : IDL.Nat,
  'createdAt' : Timestamp,
  'passengerCount' : IDL.Nat,
  'assignedDriverId' : IDL.Opt(UserId),
  'rideType' : IDL.Text,
  'datetime' : IDL.Text,
  'pickupLocation' : IDL.Text,
});
export const TransactionType = IDL.Variant({
  'credit' : IDL.Null,
  'debit' : IDL.Null,
});
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'date' : Timestamp,
  'description' : IDL.Text,
  'txType' : TransactionType,
  'amount' : IDL.Nat,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const VendorType = IDL.Variant({
  'service' : IDL.Null,
  'shop' : IDL.Null,
  'driver' : IDL.Null,
});
export const VendorPublic = IDL.Record({
  'id' : IDL.Nat,
  'contactInfo' : IDL.Text,
  'offerings' : IDL.Vec(Listing),
  'ownerId' : UserId,
  'name' : IDL.Text,
  'approvalStatus' : ApprovalStatus,
  'earnings' : IDL.Nat,
  'rating' : IDL.Float64,
  'registeredAt' : Timestamp,
  'vendorType' : VendorType,
});
export const WalletPublic = IDL.Record({
  'balance' : IDL.Nat,
  'userId' : UserId,
  'transactions' : IDL.Vec(Transaction),
});
export const AdminApprovalPublic = IDL.Record({
  'decision' : ApprovalStatus,
  'reviewedDate' : IDL.Opt(Timestamp),
  'rejectionReason' : IDL.Opt(IDL.Text),
  'reviewedBy' : IDL.Opt(UserId),
  'vendorId' : IDL.Nat,
  'submissionDate' : Timestamp,
});
export const BusStop = IDL.Record({
  'arrivalTime' : IDL.Text,
  'name' : IDL.Text,
});
export const BusRoute = IDL.Record({
  'id' : IDL.Nat,
  'arrivalTime' : IDL.Text,
  'departureTime' : IDL.Text,
  'routeName' : IDL.Text,
  'availability' : IDL.Nat,
  'stops' : IDL.Vec(BusStop),
  'price' : IDL.Nat,
});
export const RegisterUserInput = IDL.Record({
  'preferredLanguage' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const RegisterVendorInput = IDL.Record({
  'contactInfo' : IDL.Text,
  'name' : IDL.Text,
  'vendorType' : VendorType,
});
export const RequestRideInput = IDL.Record({
  'dropoffLocation' : IDL.Text,
  'passengerCount' : IDL.Nat,
  'rideType' : IDL.Text,
  'datetime' : IDL.Text,
  'pickupLocation' : IDL.Text,
});

export const idlService = IDL.Service({
  'addListing' : IDL.Func([ListingInput], [IDL.Opt(Listing)], []),
  'approveVendor' : IDL.Func([IDL.Nat], [], []),
  'bookAppointment' : IDL.Func([BookAppointmentInput], [Appointment], []),
  'cancelAppointment' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'cancelRide' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getDoctor' : IDL.Func([IDL.Nat], [IDL.Opt(Doctor)], ['query']),
  'getMyAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserPublic)], ['query']),
  'getMyRides' : IDL.Func([], [IDL.Vec(RideRequest)], ['query']),
  'getMyTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getMyVendorProfile' : IDL.Func([], [IDL.Opt(VendorPublic)], ['query']),
  'getMyWallet' : IDL.Func([], [IDL.Opt(WalletPublic)], ['query']),
  'getPendingApprovals' : IDL.Func(
      [],
      [IDL.Vec(AdminApprovalPublic)],
      ['query'],
    ),
  'listApprovedVendors' : IDL.Func([], [IDL.Vec(VendorPublic)], ['query']),
  'listBusRoutes' : IDL.Func([], [IDL.Vec(BusRoute)], ['query']),
  'listDoctors' : IDL.Func([], [IDL.Vec(Doctor)], ['query']),
  'registerUser' : IDL.Func([RegisterUserInput], [UserPublic], []),
  'registerVendor' : IDL.Func([RegisterVendorInput], [VendorPublic], []),
  'rejectVendor' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'removeListing' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'requestRide' : IDL.Func([RequestRideInput], [RideRequest], []),
  'updateListing' : IDL.Func([IDL.Nat, ListingInput], [IDL.Bool], []),
  'updateProfile' : IDL.Func([RegisterUserInput], [IDL.Opt(UserPublic)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ListingInput = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Nat,
  });
  const Listing = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Nat,
  });
  const VisitType = IDL.Variant({ 'clinic' : IDL.Null, 'home' : IDL.Null });
  const BookAppointmentInput = IDL.Record({
    'doctorId' : IDL.Nat,
    'visitType' : VisitType,
    'notes' : IDL.Text,
    'dateTime' : IDL.Text,
  });
  const AppointmentStatus = IDL.Variant({
    'scheduled' : IDL.Null,
    'cancelled' : IDL.Null,
    'completed' : IDL.Null,
  });
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const Appointment = IDL.Record({
    'id' : IDL.Nat,
    'status' : AppointmentStatus,
    'doctorId' : IDL.Nat,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'visitType' : VisitType,
    'notes' : IDL.Text,
    'dateTime' : IDL.Text,
  });
  const AvailabilitySlot = IDL.Record({
    'startTime' : IDL.Text,
    'endTime' : IDL.Text,
    'date' : IDL.Text,
    'isBooked' : IDL.Bool,
  });
  const Doctor = IDL.Record({
    'id' : IDL.Nat,
    'availabilitySlots' : IDL.Vec(AvailabilitySlot),
    'name' : IDL.Text,
    'qualifications' : IDL.Vec(IDL.Text),
    'specialization' : IDL.Text,
    'rating' : IDL.Float64,
    'hourlyPrice' : IDL.Nat,
    'visitTypes' : IDL.Vec(VisitType),
  });
  const Role = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'vendor' : IDL.Null,
    'driver' : IDL.Null,
  });
  const UserPublic = IDL.Record({
    'id' : UserId,
    'preferredLanguage' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : Role,
    'savedAddresses' : IDL.Vec(IDL.Text),
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const RideStatus = IDL.Variant({
    'assigned' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const RideRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : RideStatus,
    'dropoffLocation' : IDL.Text,
    'userId' : UserId,
    'fare' : IDL.Nat,
    'createdAt' : Timestamp,
    'passengerCount' : IDL.Nat,
    'assignedDriverId' : IDL.Opt(UserId),
    'rideType' : IDL.Text,
    'datetime' : IDL.Text,
    'pickupLocation' : IDL.Text,
  });
  const TransactionType = IDL.Variant({
    'credit' : IDL.Null,
    'debit' : IDL.Null,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'date' : Timestamp,
    'description' : IDL.Text,
    'txType' : TransactionType,
    'amount' : IDL.Nat,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const VendorType = IDL.Variant({
    'service' : IDL.Null,
    'shop' : IDL.Null,
    'driver' : IDL.Null,
  });
  const VendorPublic = IDL.Record({
    'id' : IDL.Nat,
    'contactInfo' : IDL.Text,
    'offerings' : IDL.Vec(Listing),
    'ownerId' : UserId,
    'name' : IDL.Text,
    'approvalStatus' : ApprovalStatus,
    'earnings' : IDL.Nat,
    'rating' : IDL.Float64,
    'registeredAt' : Timestamp,
    'vendorType' : VendorType,
  });
  const WalletPublic = IDL.Record({
    'balance' : IDL.Nat,
    'userId' : UserId,
    'transactions' : IDL.Vec(Transaction),
  });
  const AdminApprovalPublic = IDL.Record({
    'decision' : ApprovalStatus,
    'reviewedDate' : IDL.Opt(Timestamp),
    'rejectionReason' : IDL.Opt(IDL.Text),
    'reviewedBy' : IDL.Opt(UserId),
    'vendorId' : IDL.Nat,
    'submissionDate' : Timestamp,
  });
  const BusStop = IDL.Record({ 'arrivalTime' : IDL.Text, 'name' : IDL.Text });
  const BusRoute = IDL.Record({
    'id' : IDL.Nat,
    'arrivalTime' : IDL.Text,
    'departureTime' : IDL.Text,
    'routeName' : IDL.Text,
    'availability' : IDL.Nat,
    'stops' : IDL.Vec(BusStop),
    'price' : IDL.Nat,
  });
  const RegisterUserInput = IDL.Record({
    'preferredLanguage' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const RegisterVendorInput = IDL.Record({
    'contactInfo' : IDL.Text,
    'name' : IDL.Text,
    'vendorType' : VendorType,
  });
  const RequestRideInput = IDL.Record({
    'dropoffLocation' : IDL.Text,
    'passengerCount' : IDL.Nat,
    'rideType' : IDL.Text,
    'datetime' : IDL.Text,
    'pickupLocation' : IDL.Text,
  });
  
  return IDL.Service({
    'addListing' : IDL.Func([ListingInput], [IDL.Opt(Listing)], []),
    'approveVendor' : IDL.Func([IDL.Nat], [], []),
    'bookAppointment' : IDL.Func([BookAppointmentInput], [Appointment], []),
    'cancelAppointment' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'cancelRide' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getDoctor' : IDL.Func([IDL.Nat], [IDL.Opt(Doctor)], ['query']),
    'getMyAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserPublic)], ['query']),
    'getMyRides' : IDL.Func([], [IDL.Vec(RideRequest)], ['query']),
    'getMyTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getMyVendorProfile' : IDL.Func([], [IDL.Opt(VendorPublic)], ['query']),
    'getMyWallet' : IDL.Func([], [IDL.Opt(WalletPublic)], ['query']),
    'getPendingApprovals' : IDL.Func(
        [],
        [IDL.Vec(AdminApprovalPublic)],
        ['query'],
      ),
    'listApprovedVendors' : IDL.Func([], [IDL.Vec(VendorPublic)], ['query']),
    'listBusRoutes' : IDL.Func([], [IDL.Vec(BusRoute)], ['query']),
    'listDoctors' : IDL.Func([], [IDL.Vec(Doctor)], ['query']),
    'registerUser' : IDL.Func([RegisterUserInput], [UserPublic], []),
    'registerVendor' : IDL.Func([RegisterVendorInput], [VendorPublic], []),
    'rejectVendor' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'removeListing' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'requestRide' : IDL.Func([RequestRideInput], [RideRequest], []),
    'updateListing' : IDL.Func([IDL.Nat, ListingInput], [IDL.Bool], []),
    'updateProfile' : IDL.Func([RegisterUserInput], [IDL.Opt(UserPublic)], []),
  });
};

export const init = ({ IDL }) => { return []; };