/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminApprovalPublic {
  'decision' : ApprovalStatus,
  'reviewedDate' : [] | [Timestamp],
  'rejectionReason' : [] | [string],
  'reviewedBy' : [] | [UserId],
  'vendorId' : bigint,
  'submissionDate' : Timestamp,
}
export interface Appointment {
  'id' : bigint,
  'status' : AppointmentStatus,
  'doctorId' : bigint,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'visitType' : VisitType,
  'notes' : string,
  'dateTime' : string,
}
export type AppointmentStatus = { 'scheduled' : null } |
  { 'cancelled' : null } |
  { 'completed' : null };
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface AvailabilitySlot {
  'startTime' : string,
  'endTime' : string,
  'date' : string,
  'isBooked' : boolean,
}
export interface BookAppointmentInput {
  'doctorId' : bigint,
  'visitType' : VisitType,
  'notes' : string,
  'dateTime' : string,
}
export interface BusRoute {
  'id' : bigint,
  'arrivalTime' : string,
  'departureTime' : string,
  'routeName' : string,
  'availability' : bigint,
  'stops' : Array<BusStop>,
  'price' : bigint,
}
export interface BusStop { 'arrivalTime' : string, 'name' : string }
export interface Doctor {
  'id' : bigint,
  'availabilitySlots' : Array<AvailabilitySlot>,
  'name' : string,
  'qualifications' : Array<string>,
  'specialization' : string,
  'rating' : number,
  'hourlyPrice' : bigint,
  'visitTypes' : Array<VisitType>,
}
export interface Listing {
  'id' : bigint,
  'title' : string,
  'description' : string,
  'category' : string,
  'price' : bigint,
}
export interface ListingInput {
  'title' : string,
  'description' : string,
  'category' : string,
  'price' : bigint,
}
export interface RegisterUserInput {
  'preferredLanguage' : string,
  'name' : string,
  'email' : string,
  'phone' : string,
}
export interface RegisterVendorInput {
  'contactInfo' : string,
  'name' : string,
  'vendorType' : VendorType,
}
export interface RequestRideInput {
  'dropoffLocation' : string,
  'passengerCount' : bigint,
  'rideType' : string,
  'datetime' : string,
  'pickupLocation' : string,
}
export interface RideRequest {
  'id' : bigint,
  'status' : RideStatus,
  'dropoffLocation' : string,
  'userId' : UserId,
  'fare' : bigint,
  'createdAt' : Timestamp,
  'passengerCount' : bigint,
  'assignedDriverId' : [] | [UserId],
  'rideType' : string,
  'datetime' : string,
  'pickupLocation' : string,
}
export type RideStatus = { 'assigned' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export type Role = { 'admin' : null } |
  { 'user' : null } |
  { 'vendor' : null } |
  { 'driver' : null };
export type Timestamp = bigint;
export interface Transaction {
  'id' : bigint,
  'date' : Timestamp,
  'description' : string,
  'txType' : TransactionType,
  'amount' : bigint,
}
export type TransactionType = { 'credit' : null } |
  { 'debit' : null };
export type UserId = Principal;
export interface UserPublic {
  'id' : UserId,
  'preferredLanguage' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'role' : Role,
  'savedAddresses' : Array<string>,
  'email' : string,
  'phone' : string,
}
export interface VendorPublic {
  'id' : bigint,
  'contactInfo' : string,
  'offerings' : Array<Listing>,
  'ownerId' : UserId,
  'name' : string,
  'approvalStatus' : ApprovalStatus,
  'earnings' : bigint,
  'rating' : number,
  'registeredAt' : Timestamp,
  'vendorType' : VendorType,
}
export type VendorType = { 'service' : null } |
  { 'shop' : null } |
  { 'driver' : null };
export type VisitType = { 'clinic' : null } |
  { 'home' : null };
export interface WalletPublic {
  'balance' : bigint,
  'userId' : UserId,
  'transactions' : Array<Transaction>,
}
export interface _SERVICE {
  'addListing' : ActorMethod<[ListingInput], [] | [Listing]>,
  'approveVendor' : ActorMethod<[bigint], undefined>,
  'bookAppointment' : ActorMethod<[BookAppointmentInput], Appointment>,
  'cancelAppointment' : ActorMethod<[bigint], boolean>,
  'cancelRide' : ActorMethod<[bigint], boolean>,
  'getDoctor' : ActorMethod<[bigint], [] | [Doctor]>,
  'getMyAppointments' : ActorMethod<[], Array<Appointment>>,
  'getMyProfile' : ActorMethod<[], [] | [UserPublic]>,
  'getMyRides' : ActorMethod<[], Array<RideRequest>>,
  'getMyTransactions' : ActorMethod<[], Array<Transaction>>,
  'getMyVendorProfile' : ActorMethod<[], [] | [VendorPublic]>,
  'getMyWallet' : ActorMethod<[], [] | [WalletPublic]>,
  'getPendingApprovals' : ActorMethod<[], Array<AdminApprovalPublic>>,
  'listApprovedVendors' : ActorMethod<[], Array<VendorPublic>>,
  'listBusRoutes' : ActorMethod<[], Array<BusRoute>>,
  'listDoctors' : ActorMethod<[], Array<Doctor>>,
  'registerUser' : ActorMethod<[RegisterUserInput], UserPublic>,
  'registerVendor' : ActorMethod<[RegisterVendorInput], VendorPublic>,
  'rejectVendor' : ActorMethod<[bigint, string], undefined>,
  'removeListing' : ActorMethod<[bigint], boolean>,
  'requestRide' : ActorMethod<[RequestRideInput], RideRequest>,
  'updateListing' : ActorMethod<[bigint, ListingInput], boolean>,
  'updateProfile' : ActorMethod<[RegisterUserInput], [] | [UserPublic]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];