/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface RequestRideInput {
    dropoffLocation: string;
    passengerCount: bigint;
    rideType: string;
    datetime: string;
    pickupLocation: string;
}
export interface UserPublic {
    id: UserId;
    preferredLanguage: string;
    name: string;
    createdAt: Timestamp;
    role: Role;
    savedAddresses: Array<string>;
    email: string;
    phone: string;
}
export interface Listing {
    id: bigint;
    title: string;
    description: string;
    category: string;
    price: bigint;
}
export interface BusStop {
    arrivalTime: string;
    name: string;
}
export interface AvailabilitySlot {
    startTime: string;
    endTime: string;
    date: string;
    isBooked: boolean;
}
export interface BusRoute {
    id: bigint;
    arrivalTime: string;
    departureTime: string;
    routeName: string;
    availability: bigint;
    stops: Array<BusStop>;
    price: bigint;
}
export interface Transaction {
    id: bigint;
    date: Timestamp;
    description: string;
    txType: TransactionType;
    amount: bigint;
}
export type UserId = Principal;
export interface RegisterVendorInput {
    contactInfo: string;
    name: string;
    vendorType: VendorType;
}
export interface RegisterUserInput {
    preferredLanguage: string;
    name: string;
    email: string;
    phone: string;
}
export interface ListingInput {
    title: string;
    description: string;
    category: string;
    price: bigint;
}
export interface BookAppointmentInput {
    doctorId: bigint;
    visitType: VisitType;
    notes: string;
    dateTime: string;
}
export interface RideRequest {
    id: bigint;
    status: RideStatus;
    dropoffLocation: string;
    userId: UserId;
    fare: bigint;
    createdAt: Timestamp;
    passengerCount: bigint;
    assignedDriverId?: UserId;
    rideType: string;
    datetime: string;
    pickupLocation: string;
}
export interface WalletPublic {
    balance: bigint;
    userId: UserId;
    transactions: Array<Transaction>;
}
export interface VendorPublic {
    id: bigint;
    contactInfo: string;
    offerings: Array<Listing>;
    ownerId: UserId;
    name: string;
    approvalStatus: ApprovalStatus;
    earnings: bigint;
    rating: number;
    registeredAt: Timestamp;
    vendorType: VendorType;
}
export interface Doctor {
    id: bigint;
    availabilitySlots: Array<AvailabilitySlot>;
    name: string;
    qualifications: Array<string>;
    specialization: string;
    rating: number;
    hourlyPrice: bigint;
    visitTypes: Array<VisitType>;
}
export interface Appointment {
    id: bigint;
    status: AppointmentStatus;
    doctorId: bigint;
    userId: UserId;
    createdAt: Timestamp;
    visitType: VisitType;
    notes: string;
    dateTime: string;
}
export interface AdminApprovalPublic {
    decision: ApprovalStatus;
    reviewedDate?: Timestamp;
    rejectionReason?: string;
    reviewedBy?: UserId;
    vendorId: bigint;
    submissionDate: Timestamp;
}
export enum AppointmentStatus {
    scheduled = "scheduled",
    cancelled = "cancelled",
    completed = "completed"
}
export enum ApprovalStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum RideStatus {
    assigned = "assigned",
    cancelled = "cancelled",
    pending = "pending",
    completed = "completed",
    inProgress = "inProgress"
}
export enum Role {
    admin = "admin",
    user = "user",
    vendor = "vendor",
    driver = "driver"
}
export enum TransactionType {
    credit = "credit",
    debit = "debit"
}
export enum VendorType {
    service = "service",
    shop = "shop",
    driver = "driver"
}
export enum VisitType {
    clinic = "clinic",
    home = "home"
}
export interface backendInterface {
    addListing(input: ListingInput): Promise<Listing | null>;
    approveVendor(vendorId: bigint): Promise<void>;
    bookAppointment(input: BookAppointmentInput): Promise<Appointment>;
    cancelAppointment(appointmentId: bigint): Promise<boolean>;
    cancelRide(rideId: bigint): Promise<boolean>;
    getDoctor(doctorId: bigint): Promise<Doctor | null>;
    getMyAppointments(): Promise<Array<Appointment>>;
    getMyProfile(): Promise<UserPublic | null>;
    getMyRides(): Promise<Array<RideRequest>>;
    getMyTransactions(): Promise<Array<Transaction>>;
    getMyVendorProfile(): Promise<VendorPublic | null>;
    getMyWallet(): Promise<WalletPublic | null>;
    getPendingApprovals(): Promise<Array<AdminApprovalPublic>>;
    listApprovedVendors(): Promise<Array<VendorPublic>>;
    listBusRoutes(): Promise<Array<BusRoute>>;
    listDoctors(): Promise<Array<Doctor>>;
    registerUser(input: RegisterUserInput): Promise<UserPublic>;
    registerVendor(input: RegisterVendorInput): Promise<VendorPublic>;
    rejectVendor(vendorId: bigint, reason: string): Promise<void>;
    removeListing(listingId: bigint): Promise<boolean>;
    requestRide(input: RequestRideInput): Promise<RideRequest>;
    updateListing(listingId: bigint, input: ListingInput): Promise<boolean>;
    updateProfile(input: RegisterUserInput): Promise<UserPublic | null>;
}
import type { AdminApprovalPublic as _AdminApprovalPublic, Appointment as _Appointment, AppointmentStatus as _AppointmentStatus, ApprovalStatus as _ApprovalStatus, AvailabilitySlot as _AvailabilitySlot, BookAppointmentInput as _BookAppointmentInput, Doctor as _Doctor, Listing as _Listing, RegisterVendorInput as _RegisterVendorInput, RideRequest as _RideRequest, RideStatus as _RideStatus, Role as _Role, Timestamp as _Timestamp, Transaction as _Transaction, TransactionType as _TransactionType, UserId as _UserId, UserPublic as _UserPublic, VendorPublic as _VendorPublic, VendorType as _VendorType, VisitType as _VisitType, WalletPublic as _WalletPublic } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addListing(arg0: ListingInput): Promise<Listing | null> {
        if (this.processError) {
            try {
                const result = await this.actor.addListing(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addListing(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async approveVendor(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveVendor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveVendor(arg0);
            return result;
        }
    }
    async bookAppointment(arg0: BookAppointmentInput): Promise<Appointment> {
        if (this.processError) {
            try {
                const result = await this.actor.bookAppointment(to_candid_BookAppointmentInput_n2(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Appointment_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bookAppointment(to_candid_BookAppointmentInput_n2(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Appointment_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async cancelAppointment(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelAppointment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelAppointment(arg0);
            return result;
        }
    }
    async cancelRide(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelRide(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelRide(arg0);
            return result;
        }
    }
    async getDoctor(arg0: bigint): Promise<Doctor | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDoctor(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDoctor(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyAppointments(): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyAppointments();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyAppointments();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<UserPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyRides(): Promise<Array<RideRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyRides();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyRides();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyTransactions(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyTransactions();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyTransactions();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyVendorProfile(): Promise<VendorPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyVendorProfile();
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyVendorProfile();
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyWallet(): Promise<WalletPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyWallet();
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyWallet();
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingApprovals(): Promise<Array<AdminApprovalPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingApprovals();
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingApprovals();
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async listApprovedVendors(): Promise<Array<VendorPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApprovedVendors();
                return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApprovedVendors();
            return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async listBusRoutes(): Promise<Array<BusRoute>> {
        if (this.processError) {
            try {
                const result = await this.actor.listBusRoutes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listBusRoutes();
            return result;
        }
    }
    async listDoctors(): Promise<Array<Doctor>> {
        if (this.processError) {
            try {
                const result = await this.actor.listDoctors();
                return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listDoctors();
            return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerUser(arg0: RegisterUserInput): Promise<UserPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0);
                return from_candid_UserPublic_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0);
            return from_candid_UserPublic_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerVendor(arg0: RegisterVendorInput): Promise<VendorPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.registerVendor(to_candid_RegisterVendorInput_n50(this._uploadFile, this._downloadFile, arg0));
                return from_candid_VendorPublic_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerVendor(to_candid_RegisterVendorInput_n50(this._uploadFile, this._downloadFile, arg0));
            return from_candid_VendorPublic_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async rejectVendor(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectVendor(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectVendor(arg0, arg1);
            return result;
        }
    }
    async removeListing(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeListing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeListing(arg0);
            return result;
        }
    }
    async requestRide(arg0: RequestRideInput): Promise<RideRequest> {
        if (this.processError) {
            try {
                const result = await this.actor.requestRide(arg0);
                return from_candid_RideRequest_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestRide(arg0);
            return from_candid_RideRequest_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateListing(arg0: bigint, arg1: ListingInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateListing(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateListing(arg0, arg1);
            return result;
        }
    }
    async updateProfile(arg0: RegisterUserInput): Promise<UserPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AdminApprovalPublic_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdminApprovalPublic): AdminApprovalPublic {
    return from_candid_record_n45(_uploadFile, _downloadFile, value);
}
function from_candid_AppointmentStatus_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppointmentStatus): AppointmentStatus {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Appointment_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Appointment): Appointment {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_ApprovalStatus_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalStatus): ApprovalStatus {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_Doctor_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Doctor): Doctor {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_RideRequest_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RideRequest): RideRequest {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_RideStatus_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RideStatus): RideStatus {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionType_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionType): TransactionType {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_Transaction_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_UserPublic_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserPublic): UserPublic {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_VendorPublic_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VendorPublic): VendorPublic {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_VendorType_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VendorType): VendorType {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_VisitType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VisitType): VisitType {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_WalletPublic_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WalletPublic): WalletPublic {
    return from_candid_record_n42(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Listing]): Listing | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Doctor]): Doctor | null {
    return value.length === 0 ? null : from_candid_Doctor_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserPublic]): UserPublic | null {
    return value.length === 0 ? null : from_candid_UserPublic_n18(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserId]): UserId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_VendorPublic]): VendorPublic | null {
    return value.length === 0 ? null : from_candid_VendorPublic_n34(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_WalletPublic]): WalletPublic | null {
    return value.length === 0 ? null : from_candid_WalletPublic_n41(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    availabilitySlots: Array<_AvailabilitySlot>;
    name: string;
    qualifications: Array<string>;
    specialization: string;
    rating: number;
    hourlyPrice: bigint;
    visitTypes: Array<_VisitType>;
}): {
    id: bigint;
    availabilitySlots: Array<AvailabilitySlot>;
    name: string;
    qualifications: Array<string>;
    specialization: string;
    rating: number;
    hourlyPrice: bigint;
    visitTypes: Array<VisitType>;
} {
    return {
        id: value.id,
        availabilitySlots: value.availabilitySlots,
        name: value.name,
        qualifications: value.qualifications,
        specialization: value.specialization,
        rating: value.rating,
        hourlyPrice: value.hourlyPrice,
        visitTypes: from_candid_vec_n15(_uploadFile, _downloadFile, value.visitTypes)
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    preferredLanguage: string;
    name: string;
    createdAt: _Timestamp;
    role: _Role;
    savedAddresses: Array<string>;
    email: string;
    phone: string;
}): {
    id: UserId;
    preferredLanguage: string;
    name: string;
    createdAt: Timestamp;
    role: Role;
    savedAddresses: Array<string>;
    email: string;
    phone: string;
} {
    return {
        id: value.id,
        preferredLanguage: value.preferredLanguage,
        name: value.name,
        createdAt: value.createdAt,
        role: from_candid_Role_n20(_uploadFile, _downloadFile, value.role),
        savedAddresses: value.savedAddresses,
        email: value.email,
        phone: value.phone
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _RideStatus;
    dropoffLocation: string;
    userId: _UserId;
    fare: bigint;
    createdAt: _Timestamp;
    passengerCount: bigint;
    assignedDriverId: [] | [_UserId];
    rideType: string;
    datetime: string;
    pickupLocation: string;
}): {
    id: bigint;
    status: RideStatus;
    dropoffLocation: string;
    userId: UserId;
    fare: bigint;
    createdAt: Timestamp;
    passengerCount: bigint;
    assignedDriverId?: UserId;
    rideType: string;
    datetime: string;
    pickupLocation: string;
} {
    return {
        id: value.id,
        status: from_candid_RideStatus_n25(_uploadFile, _downloadFile, value.status),
        dropoffLocation: value.dropoffLocation,
        userId: value.userId,
        fare: value.fare,
        createdAt: value.createdAt,
        passengerCount: value.passengerCount,
        assignedDriverId: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.assignedDriverId)),
        rideType: value.rideType,
        datetime: value.datetime,
        pickupLocation: value.pickupLocation
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    date: _Timestamp;
    description: string;
    txType: _TransactionType;
    amount: bigint;
}): {
    id: bigint;
    date: Timestamp;
    description: string;
    txType: TransactionType;
    amount: bigint;
} {
    return {
        id: value.id,
        date: value.date,
        description: value.description,
        txType: from_candid_TransactionType_n31(_uploadFile, _downloadFile, value.txType),
        amount: value.amount
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    contactInfo: string;
    offerings: Array<_Listing>;
    ownerId: _UserId;
    name: string;
    approvalStatus: _ApprovalStatus;
    earnings: bigint;
    rating: number;
    registeredAt: _Timestamp;
    vendorType: _VendorType;
}): {
    id: bigint;
    contactInfo: string;
    offerings: Array<Listing>;
    ownerId: UserId;
    name: string;
    approvalStatus: ApprovalStatus;
    earnings: bigint;
    rating: number;
    registeredAt: Timestamp;
    vendorType: VendorType;
} {
    return {
        id: value.id,
        contactInfo: value.contactInfo,
        offerings: value.offerings,
        ownerId: value.ownerId,
        name: value.name,
        approvalStatus: from_candid_ApprovalStatus_n36(_uploadFile, _downloadFile, value.approvalStatus),
        earnings: value.earnings,
        rating: value.rating,
        registeredAt: value.registeredAt,
        vendorType: from_candid_VendorType_n38(_uploadFile, _downloadFile, value.vendorType)
    };
}
function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    balance: bigint;
    userId: _UserId;
    transactions: Array<_Transaction>;
}): {
    balance: bigint;
    userId: UserId;
    transactions: Array<Transaction>;
} {
    return {
        balance: value.balance,
        userId: value.userId,
        transactions: from_candid_vec_n28(_uploadFile, _downloadFile, value.transactions)
    };
}
function from_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    decision: _ApprovalStatus;
    reviewedDate: [] | [_Timestamp];
    rejectionReason: [] | [string];
    reviewedBy: [] | [_UserId];
    vendorId: bigint;
    submissionDate: _Timestamp;
}): {
    decision: ApprovalStatus;
    reviewedDate?: Timestamp;
    rejectionReason?: string;
    reviewedBy?: UserId;
    vendorId: bigint;
    submissionDate: Timestamp;
} {
    return {
        decision: from_candid_ApprovalStatus_n36(_uploadFile, _downloadFile, value.decision),
        reviewedDate: record_opt_to_undefined(from_candid_opt_n46(_uploadFile, _downloadFile, value.reviewedDate)),
        rejectionReason: record_opt_to_undefined(from_candid_opt_n47(_uploadFile, _downloadFile, value.rejectionReason)),
        reviewedBy: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.reviewedBy)),
        vendorId: value.vendorId,
        submissionDate: value.submissionDate
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _AppointmentStatus;
    doctorId: bigint;
    userId: _UserId;
    createdAt: _Timestamp;
    visitType: _VisitType;
    notes: string;
    dateTime: string;
}): {
    id: bigint;
    status: AppointmentStatus;
    doctorId: bigint;
    userId: UserId;
    createdAt: Timestamp;
    visitType: VisitType;
    notes: string;
    dateTime: string;
} {
    return {
        id: value.id,
        status: from_candid_AppointmentStatus_n8(_uploadFile, _downloadFile, value.status),
        doctorId: value.doctorId,
        userId: value.userId,
        createdAt: value.createdAt,
        visitType: from_candid_VisitType_n10(_uploadFile, _downloadFile, value.visitType),
        notes: value.notes,
        dateTime: value.dateTime
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    clinic: null;
} | {
    home: null;
}): VisitType {
    return "clinic" in value ? VisitType.clinic : "home" in value ? VisitType.home : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    vendor: null;
} | {
    driver: null;
}): Role {
    return "admin" in value ? Role.admin : "user" in value ? Role.user : "vendor" in value ? Role.vendor : "driver" in value ? Role.driver : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    assigned: null;
} | {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    inProgress: null;
}): RideStatus {
    return "assigned" in value ? RideStatus.assigned : "cancelled" in value ? RideStatus.cancelled : "pending" in value ? RideStatus.pending : "completed" in value ? RideStatus.completed : "inProgress" in value ? RideStatus.inProgress : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    credit: null;
} | {
    debit: null;
}): TransactionType {
    return "credit" in value ? TransactionType.credit : "debit" in value ? TransactionType.debit : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ApprovalStatus {
    return "pending" in value ? ApprovalStatus.pending : "approved" in value ? ApprovalStatus.approved : "rejected" in value ? ApprovalStatus.rejected : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    service: null;
} | {
    shop: null;
} | {
    driver: null;
}): VendorType {
    return "service" in value ? VendorType.service : "shop" in value ? VendorType.shop : "driver" in value ? VendorType.driver : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    scheduled: null;
} | {
    cancelled: null;
} | {
    completed: null;
}): AppointmentStatus {
    return "scheduled" in value ? AppointmentStatus.scheduled : "cancelled" in value ? AppointmentStatus.cancelled : "completed" in value ? AppointmentStatus.completed : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_VisitType>): Array<VisitType> {
    return value.map((x)=>from_candid_VisitType_n10(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Appointment>): Array<Appointment> {
    return value.map((x)=>from_candid_Appointment_n6(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RideRequest>): Array<RideRequest> {
    return value.map((x)=>from_candid_RideRequest_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n29(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AdminApprovalPublic>): Array<AdminApprovalPublic> {
    return value.map((x)=>from_candid_AdminApprovalPublic_n44(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_VendorPublic>): Array<VendorPublic> {
    return value.map((x)=>from_candid_VendorPublic_n34(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Doctor>): Array<Doctor> {
    return value.map((x)=>from_candid_Doctor_n13(_uploadFile, _downloadFile, x));
}
function to_candid_BookAppointmentInput_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookAppointmentInput): _BookAppointmentInput {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_RegisterVendorInput_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RegisterVendorInput): _RegisterVendorInput {
    return to_candid_record_n51(_uploadFile, _downloadFile, value);
}
function to_candid_VendorType_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VendorType): _VendorType {
    return to_candid_variant_n53(_uploadFile, _downloadFile, value);
}
function to_candid_VisitType_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VisitType): _VisitType {
    return to_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    doctorId: bigint;
    visitType: VisitType;
    notes: string;
    dateTime: string;
}): {
    doctorId: bigint;
    visitType: _VisitType;
    notes: string;
    dateTime: string;
} {
    return {
        doctorId: value.doctorId,
        visitType: to_candid_VisitType_n4(_uploadFile, _downloadFile, value.visitType),
        notes: value.notes,
        dateTime: value.dateTime
    };
}
function to_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    contactInfo: string;
    name: string;
    vendorType: VendorType;
}): {
    contactInfo: string;
    name: string;
    vendorType: _VendorType;
} {
    return {
        contactInfo: value.contactInfo,
        name: value.name,
        vendorType: to_candid_VendorType_n52(_uploadFile, _downloadFile, value.vendorType)
    };
}
function to_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VisitType): {
    clinic: null;
} | {
    home: null;
} {
    return value == VisitType.clinic ? {
        clinic: null
    } : value == VisitType.home ? {
        home: null
    } : value;
}
function to_candid_variant_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VendorType): {
    service: null;
} | {
    shop: null;
} | {
    driver: null;
} {
    return value == VendorType.service ? {
        service: null
    } : value == VendorType.shop ? {
        shop: null
    } : value == VendorType.driver ? {
        driver: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
