import type {
  AdminApproval,
  Appointment,
  BusRoute,
  Doctor,
  Listing,
  Product,
  ProductCategory,
  RideRequest,
  ServiceCategory,
  Testimonial,
  Vendor,
  WalletTransaction,
  Worker,
} from "./types";

export const serviceCategories: ServiceCategory[] = [
  {
    id: 1,
    name: "Recharge & Bills",
    description: "Mobile Top-ups, DTH, Electricity, Water & More",
    icon: "Zap",
    color: "primary",
    route: "/dashboard/recharge",
  },
  {
    id: 2,
    name: "Travel & Bookings",
    description: "Book Flights, Buses, Trains, and Hotels Easily",
    icon: "MapPin",
    color: "secondary",
    route: "/dashboard/transport",
  },
  {
    id: 3,
    name: "Local Shopping",
    description: "Order Groceries, Fresh Produce, & Local Specialties",
    icon: "ShoppingBag",
    color: "accent",
    route: "/dashboard/shopping",
  },
  {
    id: 4,
    name: "Digital Services",
    description: "Access Online Government Services, Insurance, & More",
    icon: "Globe",
    color: "primary",
    route: "/dashboard/services",
  },
  {
    id: 5,
    name: "Food & Delivery",
    description: "Discover & Order from Local Restaurants",
    icon: "UtensilsCrossed",
    color: "secondary",
    route: "/dashboard/food",
  },
  {
    id: 6,
    name: "Financial Services",
    description: "Digital Payments, Microloans, & Investment Options",
    icon: "Landmark",
    color: "accent",
    route: "/dashboard",
  },
  {
    id: 7,
    name: "Healthcare",
    description: "Book Doctors, Order Medicines, Emergency Access",
    icon: "Stethoscope",
    color: "primary",
    route: "/dashboard/healthcare",
  },
  {
    id: 8,
    name: "Transport",
    description: "Bus Schedules, Ride Sharing, Live Tracking",
    icon: "Bus",
    color: "secondary",
    route: "/dashboard/transport",
  },
];

export const doctors: Doctor[] = [
  {
    id: 1,
    name: "Dr. Priya Sharma",
    specialty: "General Physician",
    hospital: "Apollo Clinic",
    city: "Mumbai",
    rating: 4.8,
    experience: 12,
    fee: 300,
    available: true,
  },
  {
    id: 2,
    name: "Dr. Rajesh Kumar",
    specialty: "Cardiologist",
    hospital: "Fortis Hospital",
    city: "Delhi",
    rating: 4.9,
    experience: 18,
    fee: 800,
    available: true,
  },
  {
    id: 3,
    name: "Dr. Anita Nair",
    specialty: "Pediatrician",
    hospital: "Rainbow Children's Clinic",
    city: "Bengaluru",
    rating: 4.7,
    experience: 9,
    fee: 400,
    available: true,
  },
  {
    id: 4,
    name: "Dr. Suresh Patel",
    specialty: "Dermatologist",
    hospital: "Skin & Hair Clinic",
    city: "Ahmedabad",
    rating: 4.6,
    experience: 15,
    fee: 500,
    available: false,
  },
  {
    id: 5,
    name: "Dr. Meena Reddy",
    specialty: "Gynecologist",
    hospital: "Maternity Care Centre",
    city: "Hyderabad",
    rating: 4.9,
    experience: 20,
    fee: 600,
    available: true,
  },
  {
    id: 6,
    name: "Dr. Vikram Singh",
    specialty: "Orthopedic",
    hospital: "Bone & Joint Hospital",
    city: "Jaipur",
    rating: 4.5,
    experience: 14,
    fee: 700,
    available: true,
  },
];

export const appointments: Appointment[] = [
  {
    id: 1,
    doctorId: 1,
    doctorName: "Dr. Priya Sharma",
    specialty: "General Physician",
    date: "2026-04-18",
    time: "10:30 AM",
    status: "confirmed",
    fee: 300,
  },
  {
    id: 2,
    doctorId: 3,
    doctorName: "Dr. Anita Nair",
    specialty: "Pediatrician",
    date: "2026-04-22",
    time: "02:00 PM",
    status: "pending",
    fee: 400,
  },
  {
    id: 3,
    doctorId: 2,
    doctorName: "Dr. Rajesh Kumar",
    specialty: "Cardiologist",
    date: "2026-03-10",
    time: "11:00 AM",
    status: "completed",
    fee: 800,
  },
];

export const busRoutes: BusRoute[] = [
  {
    id: 1,
    routeNumber: "KA-01-Express",
    from: "Bengaluru",
    to: "Mysuru",
    departure: "06:00",
    arrival: "09:30",
    fare: 180,
    seats: 12,
    operator: "KSRTC",
    type: "express",
  },
  {
    id: 2,
    routeNumber: "MH-42-Sleeper",
    from: "Mumbai",
    to: "Pune",
    departure: "22:00",
    arrival: "04:30",
    fare: 350,
    seats: 5,
    operator: "Maharashtra ST",
    type: "sleeper",
  },
  {
    id: 3,
    routeNumber: "RJ-07-Ordinary",
    from: "Jaipur",
    to: "Ajmer",
    departure: "08:15",
    arrival: "10:00",
    fare: 95,
    seats: 22,
    operator: "Rajasthan Roadways",
    type: "ordinary",
  },
  {
    id: 4,
    routeNumber: "DL-15-Express",
    from: "Delhi",
    to: "Agra",
    departure: "07:00",
    arrival: "10:30",
    fare: 250,
    seats: 8,
    operator: "DTC",
    type: "express",
  },
  {
    id: 5,
    routeNumber: "TN-23-Express",
    from: "Chennai",
    to: "Coimbatore",
    departure: "21:30",
    arrival: "06:00",
    fare: 420,
    seats: 3,
    operator: "Tamil Nadu ST",
    type: "sleeper",
  },
];

export const rides: RideRequest[] = [
  {
    id: 1,
    from: "Indiranagar",
    to: "Whitefield",
    distance: 18,
    fare: 220,
    status: "completed",
    driverName: "Ramesh K.",
    driverRating: 4.7,
    vehicleType: "cab",
    requestedAt: "2026-04-10T14:32:00",
  },
  {
    id: 2,
    from: "Koramangala",
    to: "MG Road",
    distance: 6,
    fare: 80,
    status: "completed",
    driverName: "Sunil P.",
    driverRating: 4.9,
    vehicleType: "auto",
    requestedAt: "2026-04-08T09:15:00",
  },
  {
    id: 3,
    from: "HSR Layout",
    to: "Electronic City",
    distance: 14,
    fare: 130,
    status: "pending",
    vehicleType: "bike",
    requestedAt: "2026-04-14T08:00:00",
  },
];

export const vendors: Vendor[] = [
  {
    id: 1,
    businessName: "Sharma Kirana Store",
    ownerName: "Ramesh Sharma",
    category: "Grocery",
    city: "Mumbai",
    address: "12, Andheri West Market",
    phone: "9876543210",
    status: "approved",
    rating: 4.5,
    totalOrders: 340,
    joinedAt: "2025-10-15",
  },
  {
    id: 2,
    businessName: "Nair Ayurveda Pharma",
    ownerName: "Krishnan Nair",
    category: "Pharmacy",
    city: "Thiruvananthapuram",
    address: "45, East Fort Road",
    phone: "9845012345",
    status: "approved",
    rating: 4.8,
    totalOrders: 215,
    joinedAt: "2025-11-02",
  },
  {
    id: 3,
    businessName: "Patel Fresh Vegetables",
    ownerName: "Hasmukh Patel",
    category: "Fresh Produce",
    city: "Surat",
    address: "Old Vegetable Market, Ring Road",
    phone: "9712200100",
    status: "pending",
    rating: 0,
    totalOrders: 0,
    joinedAt: "2026-04-12",
  },
  {
    id: 4,
    businessName: "Reddy Tiffin Centre",
    ownerName: "Suresh Reddy",
    category: "Food",
    city: "Hyderabad",
    address: "78, Begumpet",
    phone: "9703000555",
    status: "approved",
    rating: 4.3,
    totalOrders: 1200,
    joinedAt: "2025-09-01",
  },
  {
    id: 5,
    businessName: "Singh Electronics",
    ownerName: "Harpreet Singh",
    category: "Electronics",
    city: "Amritsar",
    address: "Golden Market, Hall Gate",
    phone: "9814700600",
    status: "rejected",
    rating: 0,
    totalOrders: 0,
    joinedAt: "2026-03-28",
  },
];

export const listings: Listing[] = [
  {
    id: 1,
    vendorId: 1,
    name: "Basmati Rice",
    description: "Premium aged basmati rice from Punjab",
    price: 120,
    category: "Grocery",
    available: true,
    unit: "per kg",
  },
  {
    id: 2,
    vendorId: 1,
    name: "Toor Dal",
    description: "High quality split pigeon peas",
    price: 95,
    category: "Grocery",
    available: true,
    unit: "per kg",
  },
  {
    id: 3,
    vendorId: 2,
    name: "Ashwagandha Capsules",
    description: "Pure organic ashwagandha root extract",
    price: 350,
    category: "Pharmacy",
    available: true,
    unit: "60 capsules",
  },
  {
    id: 4,
    vendorId: 4,
    name: "Full Meals Thali",
    description: "Rice, 2 curries, sambar, rasam & dessert",
    price: 80,
    category: "Food",
    available: true,
    unit: "per plate",
  },
];

export const products: Product[] = [
  {
    id: 1,
    vendorId: 1,
    name: "Aashirvaad Atta",
    description: "Whole wheat atta 5kg pack",
    price: 240,
    mrp: 260,
    images: ["https://placehold.co/400x400?text=Atta"],
    category: "Atta, Rice & Dal",
    categoryIds: [1],
    inStock: true,
    stockCount: 50,
    isAvailable: true,
    rating: 4.8,
    totalReviews: 430,
  },
  {
    id: 2,
    vendorId: 1,
    name: "Amul Butter",
    description: "Pasteurised butter 500g",
    price: 250,
    mrp: 265,
    images: ["https://placehold.co/400x400?text=Butter"],
    category: "Dairy & Bread",
    categoryIds: [2],
    inStock: true,
    stockCount: 20,
    isAvailable: true,
    rating: 4.9,
    totalReviews: 890,
  },
  {
    id: 3,
    vendorId: 3,
    name: "Fresh Onion",
    description: "Farm fresh onions 1kg",
    price: 40,
    mrp: 50,
    images: ["https://placehold.co/400x400?text=Onion"],
    category: "Fresh Produce",
    categoryIds: [3],
    inStock: true,
    stockCount: 100,
    isAvailable: true,
    rating: 4.5,
    totalReviews: 120,
  },
  {
    id: 4,
    vendorId: 1,
    name: "Lays India's Magic Masala",
    description: "Crispy potato chips 50g",
    price: 20,
    mrp: 20,
    images: ["https://placehold.co/400x400?text=Lays+Masala"],
    category: "Munchies & Snacks",
    categoryIds: [4],
    inStock: true,
    stockCount: 200,
    isAvailable: true,
    rating: 4.7,
    totalReviews: 540,
  },
  {
    id: 5,
    vendorId: 1,
    name: "Coca-Cola Original Taste",
    description: "Soft Drink 750ml",
    price: 40,
    mrp: 40,
    images: ["https://placehold.co/400x400?text=Coca-Cola"],
    category: "Cold Drinks & Juices",
    categoryIds: [5],
    inStock: true,
    stockCount: 150,
    isAvailable: true,
    rating: 4.8,
    totalReviews: 310,
  },
  {
    id: 6,
    vendorId: 1,
    name: "Maggi 2-Minute Noodles",
    description: "Masala Noodles 70g (Pack of 4)",
    price: 56,
    mrp: 56,
    images: ["https://placehold.co/400x400?text=Maggi"],
    category: "Munchies & Snacks",
    categoryIds: [4],
    inStock: true,
    stockCount: 500,
    isAvailable: true,
    rating: 4.9,
    totalReviews: 1200,
  },
];

export const instamartCategories: ProductCategory[] = [
  { id: 1, name: "Atta, Rice & Dal", description: "", image: "🌾" },
  { id: 2, name: "Dairy & Bread", description: "", image: "🥛" },
  { id: 3, name: "Fresh Produce", description: "", image: "🍎" },
  { id: 4, name: "Munchies & Snacks", description: "", image: "🍿" },
  { id: 5, name: "Cold Drinks & Juices", description: "", image: "🥤" },
  { id: 6, name: "Sweet Tooth", description: "", image: "🍫" },
  { id: 7, name: "Personal Care", description: "", image: "🧴" },
  { id: 8, name: "Cleaning Essentials", description: "", image: "🧼" },
];

export const workers: Worker[] = [
  {
    id: 1,
    name: "Rajesh Kumar",
    category: "Electrician",
    rating: 4.8,
    totalReviews: 120,
    pricePerHour: 200,
    isAvailable: true,
    registeredAt: "2026-01-10T10:00:00Z",
  },
  {
    id: 2,
    name: "Sunita Devi",
    category: "Maid",
    rating: 4.9,
    totalReviews: 340,
    pricePerHour: 150,
    isAvailable: true,
    registeredAt: "2025-08-15T12:30:00Z",
  },
  {
    id: 3,
    name: "Manoj Plumbing",
    category: "Plumber",
    rating: 4.5,
    totalReviews: 80,
    pricePerHour: 250,
    isAvailable: false,
    registeredAt: "2026-03-22T09:15:00Z",
  },
];

export const walletTransactions: WalletTransaction[] = [
  {
    id: 1,
    type: "credit",
    amount: 500,
    description: "Cashback on recharge — Jio ₹299 plan",
    date: "2026-04-12",
    status: "success",
    category: "cashback",
  },
  {
    id: 2,
    type: "debit",
    amount: 300,
    description: "Doctor appointment — Dr. Priya Sharma",
    date: "2026-04-10",
    status: "success",
    category: "booking",
  },
  {
    id: 3,
    type: "debit",
    amount: 220,
    description: "Cab ride — Indiranagar to Whitefield",
    date: "2026-04-10",
    status: "success",
    category: "payment",
  },
  {
    id: 4,
    type: "credit",
    amount: 1000,
    description: "Wallet top-up via UPI",
    date: "2026-04-08",
    status: "success",
    category: "recharge",
  },
  {
    id: 5,
    type: "debit",
    amount: 95,
    description: "Grocery order — Sharma Kirana Store",
    date: "2026-04-06",
    status: "success",
    category: "payment",
  },
  {
    id: 6,
    type: "credit",
    amount: 50,
    description: "Referral bonus — Friend joined Ezy1",
    date: "2026-04-02",
    status: "success",
    category: "cashback",
  },
];

export const adminApprovals: AdminApproval[] = [
  {
    id: 1,
    vendorId: 3,
    vendorName: "Patel Fresh Vegetables",
    category: "Fresh Produce",
    city: "Surat",
    submittedAt: "2026-04-12",
    status: "pending",
  },
  {
    id: 2,
    vendorId: 5,
    vendorName: "Singh Electronics",
    category: "Electronics",
    city: "Amritsar",
    submittedAt: "2026-03-28",
    status: "rejected",
  },
  {
    id: 3,
    vendorId: 1,
    vendorName: "Sharma Kirana Store",
    category: "Grocery",
    city: "Mumbai",
    submittedAt: "2025-10-15",
    status: "approved",
  },
];

export const testimonials: Testimonial[] = [
  {
    id: 1,
    name: "Priya S.",
    city: "Mumbai",
    text: "Ezy1 has simplified my daily life! I can handle all my bill payments and local shopping from one app.",
    rating: 5,
    role: "Homemaker",
  },
  {
    id: 2,
    name: "Rahul K.",
    city: "Jaipur",
    text: "Connecting with local services has never been easier. Ezy1 helps me support small businesses in my community.",
    rating: 5,
    role: "Small Business Owner",
  },
  {
    id: 3,
    name: "Geeta Devi",
    city: "Patna",
    text: "Even in our small town, Ezy1 works perfectly. I booked a doctor and paid electricity bill all in one place.",
    rating: 4,
    role: "Teacher",
  },
  {
    id: 4,
    name: "Arjun M.",
    city: "Bengaluru",
    text: "The AI recommendations are spot on. Found exactly the right local vendor for home repairs within minutes.",
    rating: 5,
    role: "Software Engineer",
  },
  {
    id: 5,
    name: "Lakshmi R.",
    city: "Coimbatore",
    text: "Booking buses and tracking rides is so smooth. Finally an app that understands Indian transport needs.",
    rating: 4,
    role: "College Student",
  },
];

export const MOCK_WALLET_BALANCE = 1935;
export const MOCK_USER_NAME = "Amit Verma";
export const MOCK_USER_CITY = "Bengaluru";
